#!/usr/bin/env python3
"""
Examine Generated Reports

This script examines the reports generated by our test to see their actual content and quality.
"""

from pathlib import Path
import os
import json


def _extract_title(content):
    """Extract title from HTML content"""
    try:
        start = content.lower().find('<title>') + 7
        end = content.lower().find('</title>')
        if start > 6 and end > start:
            return content[start:end].strip()
    except:
        pass
    return "No title found"


def analyze_html_report(html_path):
    """Analyze an HTML report file"""
    if not html_path.exists():
        return {"error": f"File not found: {html_path}"}
    
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Basic file analysis
        analysis = {
            "file_path": str(html_path),
            "file_size": len(content),
            "file_size_kb": round(len(content) / 1024, 2)
        }
        
        # Parse HTML if it's not empty
        if len(content) < 200:
            analysis["warning"] = "File is very small, might not be complete HTML"
            analysis["content"] = content
            return analysis
        
        # Simple HTML analysis without BeautifulSoup
        analysis.update({
            "title": _extract_title(content),
            "has_head": '<head>' in content.lower(),
            "has_body": '<body>' in content.lower(),
            "css_styles": content.lower().count('<style>') + content.lower().count('<link'),
            "scripts": content.lower().count('<script'),
            "plotly_charts": content.count('Plotly.newPlot') + content.lower().count('plotly'),
            "tables": content.lower().count('<table'),
            "divs": content.lower().count('<div'),
            "sections": content.lower().count('<section'),
            "cards": content.lower().count('card'),
        })
        
        # Check for Bootstrap
        analysis["bootstrap"] = 'bootstrap' in content.lower()
        
        # Check for interactive elements
        analysis["interactive"] = any([
            'onclick' in content.lower(),
            'plotly' in content.lower(),
            'chartjs' in content.lower(),
            'd3' in content.lower()
        ])
        
        # Simple text extraction (very basic)
        analysis["text_length"] = len(content)
        analysis["content_preview"] = content[:500] + "..." if len(content) > 500 else content
        
        return analysis
        
    except Exception as e:
        return {"error": f"Failed to read file: {e}"}


def main():
    """Main analysis function"""
    print("🔍 Examining Generated Reports")
    print("=" * 50)
    
    # Find report directory
    report_dir = Path("reports")
    if not report_dir.exists():
        print(f"❌ Report directory not found: {report_dir}")
        return
    
    # Find HTML files
    html_files = list(report_dir.glob("*.html"))
    if not html_files:
        print(f"❌ No HTML files found in {report_dir}")
        # Check what files ARE there
        all_files = list(report_dir.glob("*"))
        print(f"📁 Files found in {report_dir}:")
        for f in all_files:
            print(f"  - {f.name}")
        return
    
    print(f"📁 Found {len(html_files)} HTML report files:")
    
    all_analyses = []
    
    for html_file in sorted(html_files):
        print(f"\n🔬 Analyzing: {html_file.name}")
        print("-" * 40)
        
        analysis = analyze_html_report(html_file)
        all_analyses.append(analysis)
        
        if "error" in analysis:
            print(f"❌ Error: {analysis['error']}")
            continue
        
        if "warning" in analysis:
            print(f"⚠️  Warning: {analysis['warning']}")
            if "content" in analysis:
                print(f"📄 Content: {analysis['content']}")
            continue
        
        # Print analysis results
        print(f"📊 File size: {analysis['file_size_kb']} KB")
        print(f"📝 Title: {analysis.get('title', 'N/A')}")
        print(f"📊 HTML structure:")
        print(f"  - Head: {'✅' if analysis.get('has_head') else '❌'}")
        print(f"  - Body: {'✅' if analysis.get('has_body') else '❌'}")
        print(f"  - CSS styles: {analysis.get('css_styles', 0)}")
        print(f"  - Scripts: {analysis.get('scripts', 0)}")
        print(f"  - Tables: {analysis.get('tables', 0)}")
        print(f"  - Divs: {analysis.get('divs', 0)}")
        print(f"  - Sections: {analysis.get('sections', 0)}")
        
        print(f"📈 Interactive content:")
        print(f"  - Plotly charts: {analysis.get('plotly_charts', 0)}")
        print(f"  - Interactive: {'✅' if analysis.get('interactive') else '❌'}")
        print(f"  - Bootstrap: {'✅' if analysis.get('bootstrap') else '❌'}")
        
        print(f"📖 Content length: {analysis.get('text_length', 0)} characters")
        if analysis.get('content_preview'):
            print(f"📄 Content preview:\n{analysis['content_preview'][:300]}...")
    
    # Summary
    print("\n" + "=" * 50)
    print("📊 REPORT ANALYSIS SUMMARY")
    print("=" * 50)
    
    total_files = len(html_files)
    successful_files = len([a for a in all_analyses if "error" not in a and "warning" not in a])
    problematic_files = total_files - successful_files
    
    if successful_files > 0:
        avg_size = sum(a.get('file_size_kb', 0) for a in all_analyses if "error" not in a) / len(all_analyses)
        total_charts = sum(a.get('plotly_charts', 0) for a in all_analyses)
        interactive_files = len([a for a in all_analyses if a.get('interactive')])
        
        print(f"Files analyzed: {total_files}")
        print(f"Successful reports: {successful_files}")
        print(f"Problematic reports: {problematic_files}")
        print(f"Average file size: {avg_size:.1f} KB")
        print(f"Total Plotly charts: {total_charts}")
        print(f"Interactive reports: {interactive_files}")
        
        # Recommendations
        print("\n🔍 Analysis Recommendations:")
        if avg_size < 10:
            print("⚠️  Reports are very small - may be missing content")
        if total_charts == 0:
            print("⚠️  No Plotly charts found - visualization may not be working")
        if interactive_files == 0:
            print("⚠️  No interactive content detected")
    
    # Save analysis to JSON
    analysis_file = report_dir / "analysis_results.json"
    with open(analysis_file, 'w') as f:
        json.dump(all_analyses, f, indent=2, default=str)
    
    print(f"\n💾 Detailed analysis saved to: {analysis_file}")


if __name__ == "__main__":
    main()